version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"

  - package-ecosystem: "npm"
    directory: "/packages/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
